Base Header Level: 2
latex input: metadata
latex author: $AUTHOR
latex title: $TITLE
abstract: $ABSTRACT
public abstract: $PUBLIC_ABSTRACT
bibtex: $BIBTEX
myreporttype: $REPORTTYPE
mydegree: $DEGREE
mydepartment: $DEPARTMENT
latex input: $TEMPLATE/setup.tex
latex footer: $TEMPLATE/footer.tex
