Base Header Level: 2
latex input: metadata
latex author: $AUTHOR
latex title: $TITLE
my abstract: $ABSTRACT
my public abstract: $PUBLIC_ABSTRACT
bibtex: $BIBTEX
myappendices: $APPENDICES
myreporttype: $REPORTTYPE
mydegree: $DEGREE
mydepartment: $DEPARTMENT
latex input: $TEMPLATE/setup.tex
latex footer: $TEMPLATE/footer.tex
